name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          script: |
            cd /home/ubuntu/solog/
            sudo git pull origin main
            yarn install
            yarn build
            pm2 restart solog
